### ISSUE TITLE
Build issue with template specialization in tinyprint.h (GCC 5.5.0 on Mageia 6 x86_64)

### ISSUE THREAD

**Issue by akien-mga** [calref/cboe#191]
I'm hitting a build issue on Mageia 6 x86_64 with GCC 5.5.0. It compiles fine with Clang 3.9.1 on the same system.

Note: To build with GCC, you need #190. And to reach this error, you need #189 merged to fix an earlier one.

```
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:46:88: error: specialization of 'template<class T> void ticpp::Printer::PushAttribute(std::__cxx11::string, T)' in different namespace [-fpermissive]
 template<> inline void ticpp::Printer::PushAttribute(std::string attrName, bool attrVal) {
                                                                                        ^
src/fileio/xml-parser/tinyprint.h:32:29: error:   from definition of 'template<class T> void ticpp::Printer::PushAttribute(std::__cxx11::string, T)' [-fpermissive]
   template<typename T> void PushAttribute(std::string attrName, T attrVal) {
                             ^
src/fileio/xml-parser/tinyprint.h:50:98: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> inline void ticpp::Printer::PushElement(std::string attrName, bool attrVal, bool cdata) {
                                                                                                  ^
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
src/fileio/xml-parser/tinyprint.h:54:73: error: specialization of 'template<class T> void ticpp::Printer::PushText(T, bool)' in different namespace [-fpermissive]
 template<> inline void ticpp::Printer::PushText(bool textVal, bool cdata) {
                                                                         ^
src/fileio/xml-parser/tinyprint.h:35:29: error:   from definition of 'template<class T> void ticpp::Printer::PushText(T, bool)' [-fpermissive]
   template<typename T> void PushText(T textVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:66:84: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, location pos, bool) {
                                                                                    ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:73:86: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, rectangle rect, bool) {
                                                                                      ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:82:96: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, cMonster::cAttack attack, bool) {
                                                                                                ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:91:97: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, cOutdoors::cWandering enc, bool) {
                                                                                                 ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:111:94: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, info_rect_t rect, bool cdata) {
                                                                                              ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
```

**Comment by CelticMinstrel** [comment]
I definitely recall getting this error before (on a different project) and it should be really easy to fix.

**Comment by CelticMinstrel** [comment]
That should fix the issue.

**Comment by akien-mga** [comment]
I'm still having build issues with GCC 5.5.0 after 05c9936:
```
build/obj/scenedit/scen.fileio.cpp:66:84: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, location pos, bool) {
                                                                                    ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:73:86: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, rectangle rect, bool) {
                                                                                      ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:82:96: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, cMonster::cAttack attack, bool) {
                                                                                                ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:91:97: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, cOutdoors::cWandering enc, bool) {
                                                                                                 ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
build/obj/scenedit/scen.fileio.cpp:111:94: error: specialization of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' in different namespace [-fpermissive]
 template<> void ticpp::Printer::PushElement(std::string tagName, info_rect_t rect, bool cdata) {
                                                                                              ^
In file included from build/obj/scenedit/scen.fileio.cpp:19:0:
src/fileio/xml-parser/tinyprint.h:38:29: error:   from definition of 'template<class T> void ticpp::Printer::PushElement(std::__cxx11::string, T, bool)' [-fpermissive]
   template<typename T> void PushElement(std::string tagName, T elemVal, bool cdata = false) {
                             ^
```
